// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
selector: 'app-livro-lista',
templateUrl: './livro-lista.component.html',
styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {

editoras: Array<Editora> = [];
livros: Array<Livro> = [];

constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

ngOnInit(): void {
this.servLivros.obterLivros().then(livros => {
this.livros = livros;
});
this.editoras = this.servEditora.getEditoras();
}

excluir = (codigo: string) => {
this.servLivros.excluir(codigo).then(ok => {
this.servLivros.obterLivros().then(livros => {
this.livros = livros;
});
});
}

obterNome = (codEditora: number) => this.servEditora.getNomeEditora(codEditora);

}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<main class="container">
    <h1 class="my-4">Lista de Livros</h1>
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Código</th>
          <th>Título</th>
          <th>Editora</th>
          <th>Autores</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>{{ livro.codigo }}</td>
          <td>{{ livro.titulo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
          <td>
            <button class="btn btn-danger" (click)="excluir(livro.codigo)">
              Excluir
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </main>

// clientes/livros-react/src/LivroLista.js
import { Livro } from '../src/modelo/Livro';
import { ControleLivros } from '../src/controle/ControleLivros';
import { ControleEditora } from '../src/controle/ControleEditora';
import React, { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';

function LinhaLivro(props) {

const controleEditora = new ControleEditora();
const nomeEditora = controleEditora.getNomeEditora(props.livro.codEditora);

const excluir = (codigo) => {
const controleLivro = new ControleLivros();
controleLivro.excluir(codigo).then(() => {
props.setCarregado(false);
});
};

return (
<tr>
<td>
<button type="button" className="btn btn-danger" onClick={() => excluir(props.livro.codigo)}>Excluir</button>
</td>
<td>{props.livro.codigo}</td>
<td>{props.livro.titulo}</td>
<td>{props.livro.resumo}</td>
<td>
  <ul>
    {props.livro.autores ? props.livro.autores.map((autor, index) => (
      <li key={index}>{autor}</li>
    )) : null}
  </ul>
</td>
<td>{nomeEditora}</td>
</tr>
);
}

function LivroLista() {
const [livros, setLivros] = useState([]);
const [carregado, setCarregado] = useState(false);

useEffect(() => {
if (!carregado) {
const controleLivro = new ControleLivros();
controleLivro.obterLivros().then((livros) => {
setLivros(livros);
setCarregado(true);
});
}
}, [carregado]);

const excluir = (codigo) => {
const controleLivro = new ControleLivros();
controleLivro.excluir(codigo).then(() => {
setCarregado(false);
});
};

return (
<table className="table">
<main>
<h1 className="text-center">Catálogo de Livros</h1>
<table className="mx-auto">
<thead className="table-dark">
<tr>
<th>Ação</th>
<th>Código</th>
<th>Título</th>
<th>Resumo</th>
<th>Autores</th>
<th>Editora</th>
</tr>
</thead>
<tbody>
{livros.map((livro, index) => (
<LinhaLivro
             key={index}
             livro={livro}
             setCarregado={setCarregado}
             excluir={excluir}
           />
))}
</tbody>
</table>
</main>
</table>
);
}

export default LivroLista;
