// clientes/livros-react/src/LivroDados.js
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ControleLivros } from "../src/controle/ControleLivros";
import { ControleEditora } from "../src/controle/ControleEditora";
import { Input } from 'reactstrap';
import { Label } from 'reactstrap';
import { Button } from 'reactstrap';
import { v4 as uuidv4 } from 'uuid';

function LivroDados() {
const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();
const opcoes = controleEditora.getEditoras().map((editora) => {
return { value: editora.codEditora, text: editora.nome };
});
const [titulo, setTitulo] = useState("");
const [resumo, setResumo] = useState("");
const [autores, setAutores] = useState("");
const [codEditora, setCodEditora] = useState(opcoes[0].value);
const navigate = useNavigate();

const tratarCombo = (evento) => {
const value = parseInt(evento.target.value);
setCodEditora(value);
};

const incluir = (evento) => {
  evento.preventDefault();
  const livro = {
    codigo: uuidv4(),
    titulo,
    resumo,
    autores: autores.split("\n"),
    codEditora
  };
  controleLivro.incluir(livro).then(() => {
    navigate("/");
  });
};


return (
<div class="col-md-3 mx-auto">
<div class="media">
<main>
<h1>Cadastro de Livros</h1>
<form onSubmit={incluir}>
<div>
<Label htmlFor="titulo">Título:</Label>
<input
class="form-control"
size="10"
type="text"
id="titulo"
value={titulo}
onChange={(evento) => setTitulo(evento.target.value)}
/>
</div>
<div>
<Label htmlFor="resumo">Resumo:</Label>
<textarea
type="textarea"
class="form-control"
aria-label="With textarea"
id="resumo"
value={resumo}
onChange={(evento) => setResumo(evento.target.value)}
></textarea>
</div>
<div>
<Label htmlFor="autores">Autores:</Label>
<textarea
class="form-control form-control-sm"
aria-label="With textarea"
id="autores"
value={autores}
onChange={(evento) => setAutores(evento.target.value)}
></textarea>
</div>
<div>
<Label htmlFor="editora">Editora:</Label>
<select id="inputState" class="form-select" value={codEditora} onChange={tratarCombo}>
{opcoes.map((opcao) => (
<option key={opcao.value} value={opcao.value}>
{opcao.text}
</option>
))}
</select>
</div>
<p></p>
<button type="submit" class="btn btn-primary">Incluir</button>
</form>
</main>
</div>
</div>
);
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { FormsModule } from '@angular/forms';

@Component({
selector: 'app-livro-dados',
templateUrl: './livro-dados.component.html',
styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
livro: Livro = new Livro("0", 0, '', '', []);
autoresForm: string = '';
editoras: Array<Editora> = [];

constructor(private servEditora: ControleEditoraService,
private servLivros: ControleLivrosService,
private router: Router) { }

ngOnInit(): void {
this.editoras = this.servEditora.getEditoras();
}

incluir = () => {
this.livro.autores = this.autoresForm.split('\n');
this.servLivros.incluir(this.livro)
.then(() => {
this.router.navigateByUrl('/lista');
});
}

}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<main class="container">
    <h2>Cadastro de Livro</h2>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
      </div>
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select class="form-control" id="editora" name="editora" required [(ngModel)]="livro.codEditora">
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores:</label>
        <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </form>
  </main>
